//// <auto-generated />
//using DapperSample.Infrastructure.Data;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace DapperSample.Infrastructure.Migrations
//{
//    [DbContext(typeof(ApplicationDbContext))]
//    [Migration("20250923215829_inittt")]
//    partial class inittt
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "6.0.0")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//            modelBuilder.Entity("DapperSample.Core.Entities.Category", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Categories");
//                });

//            modelBuilder.Entity("DapperSample.Core.Entities.Product", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("CategoryId")
//                        .HasColumnType("int");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<decimal>("Price")
//                        .HasColumnType("decimal(18,2)");

//                    b.HasKey("Id");

//                    b.HasIndex("CategoryId");

//                    b.ToTable("Products");
//                });

//            modelBuilder.Entity("DapperSample.Core.Entities.Tag", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Tag");
//                });

//            modelBuilder.Entity("ProductTag", b =>
//                {
//                    b.Property<int>("ProductsId")
//                        .HasColumnType("int");

//                    b.Property<int>("TagsId")
//                        .HasColumnType("int");

//                    b.HasKey("ProductsId", "TagsId");

//                    b.HasIndex("TagsId");

//                    b.ToTable("ProductTag");
//                });

//            modelBuilder.Entity("DapperSample.Core.Entities.Product", b =>
//                {
//                    b.HasOne("DapperSample.Core.Entities.Category", "Category")
//                        .WithMany("Products")
//                        .HasForeignKey("CategoryId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Category");
//                });

//            modelBuilder.Entity("ProductTag", b =>
//                {
//                    b.HasOne("DapperSample.Core.Entities.Product", null)
//                        .WithMany()
//                        .HasForeignKey("ProductsId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("DapperSample.Core.Entities.Tag", null)
//                        .WithMany()
//                        .HasForeignKey("TagsId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("DapperSample.Core.Entities.Category", b =>
//                {
//                    b.Navigation("Products");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
